# Generated by Django 4.2.9 on 2024-01-08 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='inicio',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
