# Generated by Django 4.2.9 on 2024-01-08 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazar', '0002_alter_evento_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='fim',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
